name: deploy to EC2

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          TARGET: http/BasicPythonHTTPServer
          port: 22
        with:
          script_after: |
            cd http/BasicPythonHTTPServer
            git pull origin main
            sudo docker build -t http-server . 
            sudo docker stop $(docker ps -q) || true
            sudo docker rm $(docker ps -aq) || true
            sudo docker run -d -p 8000:8000 http-server
