name: deploy to EC2

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Set up Python 
      uses: actions/setup-python@v4
      with: 
        python-version: '3.11'
      
    - name: install dependencies
      run : |
          python -m venv venv
          source venv/bin/activate
          pip install pytest requests
          sleep 5

    - name: build and run docker container
      run: |
        docker build -t http-server . 
        docker run -d -p 8000:8000 --name test-server http-server
        sleep 5

    - name: run bash test script
      run: | 
        chmod +x tests/run_tests.sh
        ./tests/run_tests.sh
      
    - name: stop docker containers 
      run: | 
        docker stop test-server http-server || true
        docker rm  test-server http-server || true
















  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          TARGET: ~/http/http/BasicPythonHTTPServer
          port: 22
        with:
          script_after: |
            cd ~/http/http/BasicPythonHTTPServer
            git fetch origin
            git reset --hard origin/main
            sudo docker build -t http-server . 
            sudo docker stop $(docker ps -q) || true
            sudo docker rm $(docker ps -aq) || true
            sudo docker run -d -p 8000:8000 http-server
            sudo docker stop prometheus || true
            sudo docker rm prometheus || true
            sudo docker run -d --network=host -v /home/ec2-user/http/http/BasicPythonHTTPServer/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus
